services:

  postgres:
    image: postgres:16
    container_name: rcp-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: rcp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - rcp-postgres-data:/var/lib/postgresql/data

volumes:
  rcp-postgres-data: